export enum PermissionGroupEnum {
  VIEW_SELF = 'VIEW_SELF',
  EDIT_SELF = 'EDIT_SELF',
  DELETE_SELF = 'DELETE_SELF',
  VIEW_ALL = 'VIEW_ALL',
  EDIT_ALL = 'EDIT_ALL',
  DELETE_ALL = 'DELETE_ALL',
}
